config/routes.rb
Rails.application.routes.draw do
  get 'artists', to: 'artists#index', as: 'artists'
  get 'artists/:id', to: 'artists#show', as: 'artist'
  devise_for :users
  resources :albums
  root to: 'artists#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord

  validates :artist_id, :name, :year, presence: true
  validates :year, numericality: { only_integer: true, less_than_or_equal_to: Date.today.year }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist
  attr_reader :id, :name, :twitter
 
  def initialize(id:, name:, twitter:)
    @id = id
    @name = name
    @twitter = twitter
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { user: 0, admin: 1 }

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 6 }
  validates :full_name, presence: true, length: { minimum: 8 }
  validates :password, presence: true, length: { minimum: 6 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :validatable, :trackable, :recoverable, :rememberable and :omniauthable
  devise :database_authenticatable, :registerable, authentication_keys: [:username]
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[show edit update destroy]
  before_action :set_artists, only: %i[edit new create]
  skip_before_action :verify_authenticity_token

  # GET /albums or /albums.json
  def index
    @albums = Album.all.page params[:page]
  end

  # GET /albums/1 or /albums/1.json
  def show; end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit; end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    if current_user.admin?
      @album.destroy
      respond_to do |format|
        format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @album, notice: 'Only Admins users can destroy Albums.' }
        format.json { head :unauthorized }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_album
    @album = Album.find(params[:id])
  end

  def set_artists
    @client = MoatClient.new
    @artists = @client.all_artists
  end

  # Only allow a list of trusted parameters through.
  def album_params
    params.require(:album).permit(:artist_id, :name, :year)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # Devise configurations for use custom field for User model
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    artists_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :full_name, :role, :password) }
    devise_parameter_sanitizer.permit :sign_in, keys: %i[username password]
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:username, :full_name, :role, :password, :current_password)
    end
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_moat_client

  def index
    @artists = Kaminari.paginate_array(@client.all_artists).page(params[:page]).per(15)
  end

  def show
    @artist = @client.find_artist(params[:id])
    @albums = Album.where({ artist_id: @artist.id })
  end

  private

  def set_moat_client
    @client = MoatClient.new
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def artist_name(artist_id)
    client = MoatClient.new
    client.find_artist(artist_id).name
  end

  def flash_class(level)
    bootstrap_alert_class = {
      'success' => 'alert-info',
      'error' => 'alert-danger',
      'notice' => 'alert-success',
      'alert' => 'alert-warning',
      'warn' => 'alert-warning'
    }
    bootstrap_alert_class[level]
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>
  <% if album.errors.any? %>
    <div class="alert alert-danger text-start" role="alert">
      <p><strong><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</strong></p>
      <ul class="list-unstyled">
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="form-outline mb-4 text-start">
    <%= form.label :artist_id, class: 'text-start form-label fw-bold' %>
    <%= form.select :artist_id, @artists.collect { |artist| [artist.name, artist.id] }, {}, { :class => 'form-control form-control-lg' } %>
    <div class="form-text" for="album_artist_id">Select one of the allowed Artists</div>
  </div>
  <div class="form-outline mb-4 text-start">
    <%= form.label :name, class: 'text-start form-label fw-bold' %>
    <%= form.text_field :name, class: "form-control form-control-lg", placeholder: "The Name of the Album" %>
    <div class="form-text" for="album_name">Album name must be at least 1 character</div>
  </div>
  <div class="form-outline mb-4 text-start">
    <%= form.label :year, class: 'text-start form-label fw-bold' %>
    <%= form.number_field :year, class: "form-control form-control-lg", placeholder: "Only Numbers" %>
    <div class="form-text" for="album_year">Only Numbers are permitted. Year must be less or equal to <%= Time.now.year %></div>
  </div>
  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary btn-lg" %>
  </div>
<% end %>
<div class="divider d-flex align-items-center my-4">
  <p class="text-center fw-bold mx-3 mb-0"></p>
</div>

app/views/albums/_new_album.html.erb
<div class="col-md-2">
  <%= link_to new_album_path, class: 'btn btn-success text-white fw-bold' do %>
    <i class="bi bi-plus-lg"></i> Add New Album
  <% end %>
</div>

app/views/albums/edit.html.erb
<div class="col-md">
  <h1>Editing Album</h1>
  <p class="lead">
    Edit informations for the Album.
  </p>
  <p class="lead text-justifed fw-bold"><span class="text-danger">All Fields are obligatory</span></p>
</div>
<%= render 'form', album: @album %>
<div class="col-md">
  <%= link_to 'Back',  albums_path, class: 'link-danger fw-bold bg-transparent' %>
</div>

app/views/albums/index.html.erb
<div class="row">
  <h1>Albums</h1>
</div>
<%= render "new_album" %>
<!-- Albuns list -->
<%= render "shared/albums_table" %>
<!-- add new album -->
<div class="col-md-4">
  <%= paginate @albums %>
</div>

app/views/albums/new.html.erb
<div class="col-md">
  <h1>New Album</h1>
  <p class="lead">
    Enter with the follwing informations to create a New Album.
  </p>
  <p class="lead text-justifed fw-bold"><span class="text-danger">All Fields are obligatory</span></p>
</div>
<%= render 'form', album: @album %>
<%= link_to 'Back',  albums_path, class: 'link-danger fw-bold bg-transparent' %>

app/views/albums/show.html.erb
<div class="container">
  <h1>
    <%= @album.name %>
  </h1>
</div>
<div class="col-md">
  <p>
    <strong>Artist:</strong>
    <%= artist_name(@album.artist_id) %>
  </p>
  <p>
    <strong>Year:</strong>
    <%= @album.year %>
  </p>
</div>
<div class="container">
  <%= link_to 'Edit', edit_album_path(@album), class: 'bg-transparent fw-bold' %> |
  <%= link_to 'Back', albums_path, class: 'bg-transparent fw-bold' %>
</div>

app/views/artists/index.html.erb
<div class="row">
  <h1>Artists</h1>
</div>
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Twitter</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @artists.each do |artist| %>
        <tr>
          <td><%= artist.name %></td>
          <td><%= artist.twitter %></td>
          <td><%= link_to 'Show', artist_path(artist.id), class: 'btn btn-primary text-white btn-sm fw-bold' %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <td class="fw-bold">Total of <%= @artists.size %> Artists</td>
    </tfoot>
  </table>
</div>
<div class="col-md-4">
  <%= paginate @artists %>
</div>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>
    <%= @artist.name %>
  </h1>
</div>
<div class="col-md">
  <p>
    <strong>Twitter:</strong>
    <%= @artist.twitter %>
  </p>
</div>
<div class="row">
  <h1>Albums</h1>
</div>
<!-- Artist Albums List -->
<%= render "shared/albums_table" %>
<div class="container">
  <%= link_to 'Back', artists_path, class: 'bg-transparent fw-bold' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMusicCollectionApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <!-- Navbar -->
    <%= render "layouts/shared/navbar" %>
    <!-- Main Content -->
    <section class="bg-white h-custom">
      <div class="container">
        <div class="row mt-5 mb-5 pb-5">
          <div class="container mt-3">
            <% flash.each do |key, message| %>
              <div class="alert <%= flash_class(key) %> alert-dismissible fade show text-center" role="alert">
                <%= message %>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            <% end %>
          </div>
          <%= yield %>
        </div>
      </div>
    </section>
    <!-- Footer -->
    <%= render "layouts/shared/footer" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMusicCollectionApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <!-- NavBar -->
    <%= render "layouts/shared/devise/navbar" %>
    <!-- Main content -->
    <section class="bg-light bg-opacity-10 vh-100 p-5 pt-lg-5 text-center text-sm-start">
      <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">          
          <%= yield %>
        </div>
      </div>
    </section>
    <!-- Footer -->
    <%= render "layouts/shared/footer" %>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer class="mt-auto bg-primary text-white text-center text-lg-start fixed-bottom">
  <div class="container">
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <div class="text-center">
        <p class="lead">Developed by <a href="https://www.linkedin.com/in/rafael-viana-75529b32/" target="_blank" class="me-4 text-reset bg-transparent fw-bold">rvlaraujo</a></p>
      </div>
    </section>
  </div>
</footer>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark py-2 fixed-top">
  <div class="container">
    <%= image_tag 'rails-collection-music-logo.svg', class: 'd-inline-block align-text-top brand-image' %>
    <%= link_to "Rails Collection Music", root_path, class: 'navbar-brand bg-transparent' %>
    <button class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navmenu">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id='navmenu'>
      <ul class="navbar-nav ms-auto fw-bold">
        <li class="nav-item">
          <%= link_to "Artistas", artists_path, class: "nav-link bg-transparent" %>
        </li>
        <li class="nav-item">
          <%= link_to "Albums", albums_path, class: "nav-link bg-transparent" %>
        </li>
        <!-- Navbar dropdown -->
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle bg-transparent"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <%= current_user.username %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="#">Hi, <%= current_user.full_name %></a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item bg-transparent" %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_albums_table.html.erb
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Year</th>
        <th>Artist</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @albums.each do |album| %>
        <tr>
          <td><%= album.name %></td>
          <td><%= album.year %></td>
          <td><%= artist_name(album.artist_id) %></td>
          <td>
            <%= link_to 'Show', album, class: 'btn btn-primary text-white btn-sm fw-bold' %>
            <%= link_to 'Edit', edit_album_path(album), class: 'btn btn-secondary text-white btn-sm fw-bold' %>
            <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger text-white btn-sm fw-bold' %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <td class="fw-bold">Total of <%= @albums.size %> Albuns</td>
    </tfoot>
  </table>
</div>